/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controlador.Registro;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import proyectofinsemestre.Libros;

/**
 *
 * @author tleon
 */
public class listadoLibros extends javax.swing.JFrame {

    /**
     * Creates new form listadoLibros
     */
    public listadoLibros() {
        initComponents();
    }
    
    
    /*class jpanelGradient extends JPanel{ //codigo para ponerle color al bg
        @Override
        protected void  paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(247,41,41);
            Color color2 = new Color(249,223,12);
            GradientPaint gp = new  GradientPaint(0,0,color1, 180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);   
        }
    }
    /*
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_lista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_buscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_1año = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_año2 = new javax.swing.JTextField();
        buscar_año = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Año de publicacion", "Numero de paginas", "Genero literario"
            }
        ));
        jScrollPane1.setViewportView(jTable_lista);

        jLabel1.setText("Filtrar por genero literario:");

        tf_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_buscarActionPerformed(evt);
            }
        });
        tf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_buscarKeyReleased(evt);
            }
        });

        jButton2.setText("Actualizar tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar por año de publicacion:");

        jLabel3.setText("De");

        text_1año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_1añoActionPerformed(evt);
            }
        });

        jLabel4.setText("Hasta");

        buscar_año.setText("Buscar");
        buscar_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_añoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_1año, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_año2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(buscar_año)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text_1año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_año2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_año)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //TODO add your handling code here:
         // O "titulo" dependiendo de tus necesidades
        buscarTablaLibros();
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_buscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        agregarLibro goAgregar = new agregarLibro();
        goAgregar.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      modificarLibro goModificar = new modificarLibro();
        goModificar.setVisible(true);
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        actualizarTablaLibros();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        eliminarLibros goLibros = new eliminarLibros();
        goLibros.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_buscarKeyReleased

    private void buscar_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_añoActionPerformed
        // TODO add your handling code here:
        buscarAñoTablaLibros();
    }//GEN-LAST:event_buscar_añoActionPerformed

    private void text_1añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_1añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_1añoActionPerformed

    private void actualizarTablaLibros() {
        ArrayList<Libros> lista = Registro.mostrarTodos();
        String matriz[][] = new String[lista.size()][6];
        for (int i = 0; i < lista.size(); i++) {
            matriz[i][0] = lista.get(i).getId() + "";
            matriz[i][1] = lista.get(i).getTitulo();
            matriz[i][2] = lista.get(i).getAutor();
            matriz[i][3] = lista.get(i).getAño_de_publicacion() + "";
            matriz[i][4] = lista.get(i).getNumero_paginas() + "";
            matriz[i][5] = lista.get(i).getGen_literario();
        }
        
        jTable_lista.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Titulo", "Autor","Año de publicacion","Numero de paginas","Genero literario"
                }
        )
                
      );
    }
    private void buscarTablaLibros() {
    ArrayList<Libros> lista = Registro.mostrarTodos();
    ArrayList<Libros> listaFiltrada = new ArrayList<>();

    String valorCriterio = tf_buscar.getText().trim().toLowerCase();

    for (Libros libro : lista) {
        // Filtrar por autor o título
        if (libro.getGen_literario().toLowerCase().contains(valorCriterio) ||
            libro.getTitulo().toLowerCase().contains(valorCriterio)) {
            listaFiltrada.add(libro);
        }
    }

    // Crear la matriz con los resultados filtrados
    String matriz[][] = new String[listaFiltrada.size()][6];
    for (int i = 0; i < listaFiltrada.size(); i++) {
        matriz[i][0] = listaFiltrada.get(i).getId() + "";
        matriz[i][1] = listaFiltrada.get(i).getTitulo();
        matriz[i][2] = listaFiltrada.get(i).getAutor();
        matriz[i][3] = listaFiltrada.get(i).getAño_de_publicacion() + "";
        matriz[i][4] = listaFiltrada.get(i).getNumero_paginas() + "";
        matriz[i][5] = listaFiltrada.get(i).getGen_literario();
    }

    // Configurar el modelo de la tabla con la nueva matriz
    jTable_lista.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String[]{
                "ID", "Titulo", "Autor", "Año de publicacion", "Numero de paginas", "Genero literario"
            }
    ));
    }
    private void buscarAñoTablaLibros() {
    ArrayList<Libros> lista = Registro.mostrarTodos();
    ArrayList<Libros> listaFiltrada = new ArrayList<>();

    String valorCriterio = tf_buscar.getText().trim().toLowerCase();
    int añoMinimo = Integer.parseInt(text_1año.getText().trim());
    int añoMaximo = Integer.parseInt(txt_año2.getText().trim());

    for (Libros libro : lista) {
        // Filtrar por género literario, título o autor
        boolean cumpleConCriterio = libro.getGen_literario().toLowerCase().contains(valorCriterio) ||
                                    libro.getTitulo().toLowerCase().contains(valorCriterio) ||
                                    libro.getAutor().toLowerCase().contains(valorCriterio);

        // Filtrar por rango de años de publicación
        boolean estaEnRango = libro.getAño_de_publicacion() >= añoMinimo && libro.getAño_de_publicacion() <= añoMaximo;

        if (cumpleConCriterio && estaEnRango) {
            listaFiltrada.add(libro);
        }
    }

    // Crear la matriz con los resultados filtrados
    String matriz[][] = new String[listaFiltrada.size()][6];
    for (int i = 0; i < listaFiltrada.size(); i++) {
        matriz[i][0] = listaFiltrada.get(i).getId() + "";
        matriz[i][1] = listaFiltrada.get(i).getTitulo();
        matriz[i][2] = listaFiltrada.get(i).getAutor();
        matriz[i][3] = listaFiltrada.get(i).getAño_de_publicacion() + "";
        matriz[i][4] = listaFiltrada.get(i).getNumero_paginas() + "";
        matriz[i][5] = listaFiltrada.get(i).getGen_literario();
    }

    // Configurar el modelo de la tabla con la nueva matriz
    jTable_lista.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String[]{
                "ID", "Titulo", "Autor", "Año de publicacion", "Numero de paginas", "Genero literario"
            }
    ));
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_año;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_lista;
    private javax.swing.JTextField text_1año;
    private javax.swing.JTextField tf_buscar;
    private javax.swing.JTextField txt_año2;
    // End of variables declaration//GEN-END:variables
}
